# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='following',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
