# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0002_auto_20151227_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('Confirm_Password', models.CharField(max_length=200)),
                ('Email_Id', models.CharField(max_length=200)),
            ],
        ),
    ]
